## static_countries
UPDATE static_countries SET cn_short_sr='Andora' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_sr='Ujedinjeni Arapski Emirati' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_sr='Afganistan' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_sr='Antigva i Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_sr='Angvila' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_sr='Albanija' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_sr='Armenija' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_sr='Holandski Antili' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_sr='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_sr='Antarktika' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_sr='Argentina' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_sr='Američka Samoa' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_sr='Austrija' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_sr='Australija' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_sr='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_sr='Azerbejdžan' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_sr='Bosna i Hercegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_sr='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_sr='Bangladeš' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_sr='Belgija' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_sr='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_sr='Bugarska' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_sr='Bahrein' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_sr='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_sr='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_sr='Bermudi' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_sr='Bruneji' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_sr='Bolivija' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_sr='Brazil' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_sr='Bahami' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_sr='Butan' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_sr='Buve' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_sr='Bocvana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_sr='Bolorusija' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_sr='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_sr='Kanada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_sr='Kokosova Ostrva' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_sr='Demokratska Republika Kongo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_sr='Centralnoafrička Republika' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_sr='Republika Kongo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_sr='Švajcarska' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_sr='Obala Slonovače' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_sr='Kukova Ostrva' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_sr='Čile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_sr='Kamerun' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_sr='Kina' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_sr='Kolumbija' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_sr='Kostarika' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_sr='Kuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_sr='Zelenortska Ostrva' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_sr='Božićno Ostrvo' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_sr='Kipar' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_sr='Češka' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_sr='Nemačka' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_sr='Džibuti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_sr='Danska' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_sr='Dominika ' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_sr='Dominikanska Republika' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_sr='Alžir' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_sr='Ekvador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_sr='Estonija' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_sr='Egipat' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_sr='Zapadna Sahara' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_sr='Eritreja' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_sr='Španija' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_sr='Etiopija' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_sr='Finska' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_sr='Fidži' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_sr='Foklandska Ostrva' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_sr='Mikronezija' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_sr='Farska Ostrva' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_sr='Francuska' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_sr='Gabon' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_sr='Velika Britanija' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_sr='Granada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_sr='Gruzija' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_sr='Francuska Gvajana' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_sr='Gana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_sr='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_sr='Grenland' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_sr='Gambija' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_sr='Gvineja' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_sr='Gvadelup' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_sr='Ekvatorijalna Gvineja' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_sr='Grčka' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_sr='Južna Džordžija i Južna Sedvička Ostrva' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_sr='Gvatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_sr='Gvam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_sr='Gvineja Bisao' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_sr='Gvajana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_sr='Hong Kong' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_sr='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_sr='Hrvatska' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_sr='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_sr='Mađarska' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_sr='Indonezija' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_sr='Irska' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_sr='Izrael' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_sr='Indija' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_sr='Britanska teritorija Indijskog okeana' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_sr='Irak' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_sr='Iran' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_sr='Island' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_sr='Italija' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_sr='Jamajka' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_sr='Jordan' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_sr='Japan' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_sr='Kenija' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_sr='Kirgistan' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_sr='Kambodža' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_sr='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_sr='Komori' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_sr='Sent Kits i Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_sr='Severna Koreja' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_sr='Južna Koreja' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_sr='Kuvajt' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_sr='Kajmanska Ostrva' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_sr='Kazahstan' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_sr='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_sr='Liban' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_sr='Sveta Lucija' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_sr='Lihtenštajn' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_sr='Šri Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_sr='Liberija' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_sr='Lesoto' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_sr='Litvanija' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_sr='Luksemburg' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_sr='Latvija' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_sr='Libija' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_sr='Maroko' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_sr='Monako' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_sr='Moldova' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_sr='Madagaskar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_sr='Maršalska Ostrva' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_sr='Makedonija' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_sr='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_sr='Mijanmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_sr='Mongolija' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_sr='Makao' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_sr='Severna Marijanska Ostrva' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_sr='Martinik' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_sr='Mauritanija' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_sr='Monserat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_sr='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_sr='Mauricijus' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_sr='Maldivi' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_sr='Malavi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_sr='Meksiko' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_sr='Malezija' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_sr='Mozambik' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_sr='Namibija' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_sr='Nova Kaledonija' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_sr='Niger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_sr='Norfok' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_sr='Nigerija' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_sr='Nikaragva' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_sr='Holandija' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_sr='Norveška' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_sr='Nepal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_sr='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_sr='Nijue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_sr='Novi Zeland' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_sr='Oman' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_sr='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_sr='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_sr='Francuska Polinezija' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_sr='Papua Nova Gvineja' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_sr='Filipini' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_sr='Pakistan' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_sr='Poljska' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_sr='Sen Pjer i Mikelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_sr='Ostrva Pitkern' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_sr='Portoriko' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_sr='Portugalija' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_sr='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_sr='Paragvaj' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_sr='Katar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_sr='Reinion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_sr='Rumunija' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_sr='Rusija' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_sr='Ruanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_sr='Saudijska Arabija' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_sr='Solomonova Ostrva' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_sr='Sejšeli' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_sr='Sudan' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_sr='Švedska' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_sr='Singapur' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_sr='Sveta Helena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_sr='Slovenija' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_sr='Svalbard' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_sr='Slovačka' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_sr='Sijera Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_sr='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_sr='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_sr='Somalija' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_sr='Surinam' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_sr='Sao Tome i Prinsipe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_sr='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_sr='Sirija' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_sr='Svazilend' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_sr='Turks i Kajkos' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_sr='Čad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_sr='Francuske južne i antarktičke zemlje' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_sr='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_sr='Tajland' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_sr='Tadžikistan' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_sr='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_sr='Turkmenistan' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_sr='Tunis' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_sr='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_sr='Istočni Timor' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_sr='Turska' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_sr='Trinidad i Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_sr='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_sr='Tajvan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_sr='Tanzanija' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_sr='Ukrajina' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_sr='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_sr='Američka Okeanija' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_sr='Sjedinjene Američke Države' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_sr='Urugvaj' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_sr='Uzbekistan' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_sr='Vatikan' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_sr='Sent Vinsent i Grenadini' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_sr='Venecuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_sr='Britanska Devičanska Ostrva' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_sr='Američka Devičanska Ostvra' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_sr='Vijetnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_sr='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_sr='Valis i Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_sr='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_sr='Jemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_sr='Majot' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_sr='Južna Afrika' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_sr='Zambija' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_sr='Zimbabve' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_sr='Palestina' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_sr='Srbija i Crna Gora' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_sr='Olandska Ostrva' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_sr='Ostrva Herd i Mekdonald' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_sr='Crna Gora' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_sr='Srbija   ' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_sr='Džerzi' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_sr='Gernzi' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_sr='Ostrvo Men' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_sr='Sveti Martin' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_sr='Sent Bartelemi' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_sr='Karipska Holandija' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_sr='Kurasao' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_sr='Sveti Martin' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_sr='Južni Sudan' WHERE cn_iso_2='SS';